[package]
name = "carcara"
version = "1.1.0"
authors = [
    "Bruno Andreotti <bandreotti@proton.me>",
    "Haniel Barbosa <hanielbbarbosa@gmail.com>",
    "Vinicius Gomes <vinicius.svgomes@gmail.com>",
    "Bernardo Borges <bernborgess@outlook.com>",
    "Tiago Campos <tiagocampos@mixrank.com>",
]
edition = "2024"
rust-version = "1.93"
license = "Apache-2.0"

[dependencies]
carcara-macros = { path = "carcara-macros" }
clap = { version = "4.6.6", features = ["derive"] }
crossbeam-queue = "0.3.13"
ansi_term = "0.12"
indexmap = "2.14.0"
log = { version = "0.4.34", features = ["std"] }
rapidhash = "4.5.1"
rug = { version = "1.30.0", default-features = false, features = [
    "integer",
    "rational",
] }
thiserror = "2.0.20"
nom = "8.0.0"
itertools = "0.11"
try_match = "0.4.1"
pretty = "0.12.3"

[dev-dependencies]
test-generator = { path = "test-generator" }
rand = "0.10.2"
colored = "3.1.1"

[[bin]]
name = "carcara"
path = "src/bin/cli/main.rs"

[workspace]
members = ["carcara-macros", "test-generator"]
resolver = "2"

[profile.release]
debug = 1
incremental = true

[profile.release-lto]
inherits = "release"
debug = 0
incremental = false
lto = true
