#!/usr/bin/env bash
# Verifies the correctness of the concurrent implementation of carcara comparing
#  the result generated by the single thread execution and a parallel execution.
# Receives a single argument that is the directory path that contains the files 
#  to be used in the test

DIR=$1

aaa=$(pwd);
FULL_DIR="$aaa/$DIR";
cd $FULL_DIR
global_count=0

for dir in $(find $FULL_DIR -maxdepth 6 -type d); do
    echo $'\e[1;34m'$dir$':\e[0m'

    count=0
    for FILE in $dir/*.smt_in; do
        RESULT1=$(cargo run -- check --skip-unknown-rules -u 1 "$FILE.proof" "$FILE" 2>/dev/null &)
        RESULT2=$(cargo run --features thread-safety -- check --skip-unknown-rules -u 3 "$FILE.proof" "$FILE" 2>/dev/null &)

        RESULT1=$(echo $RESULT1 | tr '\a' ' ' | awk '{print $NF}')
        RESULT2=$(echo $RESULT2 | tr '\a' ' ' | awk '{print $NF}')

        if [ "$RESULT1" == "" ] || [ "$RESULT2" == "" ]; then
            echo;
            echo $'\e[1;31mPanicked at '$(basename $FILE)$'\e[0m';
            echo;
            exit 0;
        fi

        DIF="EQUAL"
        if [ "$RESULT1" != "$RESULT2" ]; then
            DIF="DIF"
            ((count = count + 1))
            ((global_count = global_count + 1))
            echo $''$(basename $FILE)$': '$RESULT1$' is \e[1;31m'$DIF$'\e[0m from '$RESULT2$'';
        else
            echo $''$(basename $FILE)$': '$RESULT1$' is \e[1;32m'$DIF$'\e[0m from '$RESULT2$'';
        fi
    done
    
    echo $'Different count: \e[1;33m'$count$'\e[0m';
    echo;
done

echo;
echo $'Global count: \e[1;33m'$global_count$'\e[0m';