//! Helpers for checking and elaborating `resolution` steps.

use crate::ast::{Rc, Term, build_term, pool::Pool};
use indexmap::{IndexMap, IndexSet, map::Entry};
use thiserror::Error;

/// Errors related to the resolution checking and elaboration algorithms.
#[derive(Debug, Error)]
pub enum ResolutionError {
    /// The premise clause did not contain a literal and its negation (that is, it was not a
    /// tautology).
    #[error("couldn't find tautology in clause")]
    TautologyFailed,

    /// A pivot was not eliminated from the conclusion clause.
    #[error("pivot was not eliminated: '{0}'")]
    RemainingPivot(Rc<Term>),

    /// A term present in the conclusion clause was not produced by the resolution.
    #[error("term in conclusion was not produced by resolution: '{0}'")]
    ExtraTermInConclusion(Rc<Term>),

    /// A term produced by the resolution is missing from the conclusion clause.
    #[error("term produced by resolution is missing in conclusion: '{0}'")]
    MissingTermInConclusion(Rc<Term>),

    /// The given pivot was not found in the clause where it was expected.
    #[error("pivot was not found in clause: '{0}'")]
    PivotNotFound(Rc<Term>),

    /// The Reverse Unit Propagation resolution check failed.
    #[error("RUP resolution failed")]
    RupFailed,
}

/// A literal: a term together with the number of leading negations applied to it.
///
/// This is the representation produced by [`Rc<Term>::remove_all_negations`], and can be
/// converted back into a term with [`literal_to_term`].
pub type Literal<'a> = (u32, &'a Rc<Term>);

/// A collection of [`Literal`]s that can be used as a clause during resolution.
///
/// This can be either a [`Vec`] or an [`IndexSet`], depending on the needed clause semantics.
pub trait ClauseCollection<'a>: FromIterator<Literal<'a>> {
    /// Inserts a literal into the clause.
    fn insert_term(&mut self, item: Literal<'a>);

    /// Removes a literal from the clause, returning `true` if it was present.
    fn remove_term(&mut self, item: &Literal<'a>) -> bool;
}

impl<'a> ClauseCollection<'a> for Vec<Literal<'a>> {
    fn insert_term(&mut self, item: Literal<'a>) {
        self.push(item);
    }

    fn remove_term(&mut self, item: &Literal<'a>) -> bool {
        if let Some(pos) = self.iter().position(|x| x == item) {
            self.remove(pos);
            true
        } else {
            false
        }
    }
}

impl<'a> ClauseCollection<'a> for IndexSet<Literal<'a>> {
    fn insert_term(&mut self, item: Literal<'a>) {
        self.insert(item);
    }

    fn remove_term(&mut self, item: &Literal<'a>) -> bool {
        self.swap_remove(item)
    }
}

/// Transforms a `Literal` into an `Rc<Term>`, undoing the transformation done by
/// `Rc<Term>::remove_all_negations`.
pub fn literal_to_term(pool: &mut Pool, (n, term): Literal) -> Rc<Term> {
    let mut term = term.clone();
    for _ in 0..n {
        term = build_term!(pool, (not { term }));
    }
    term
}

/// The result of [`greedy_resolution`].
///
/// This records the pivot used in each binary resolution step, as well as a flag indicating
/// whether a double negation was implicitly added to the conclusion.
pub struct ResolutionTrace {
    /// Whether the conclusion clause contains a single term with an extra even number of leading
    /// negations.
    ///
    /// This is a quirk found in proofs generated by veriT, where a resolution step that should
    /// conclude `(cl f)` instead concludes `(cl (not (not f)))` or similar.
    pub not_not_added: bool,

    /// The pivot used in each binary resolution step, in order, together with its polarity.
    ///
    /// The polarity is `true` if the pivot appears with positive polarity in the left-hand clause,
    /// and `false` otherwise.
    pub pivot_trace: Vec<(Rc<Term>, bool)>,
}

/// Checks a `resolution` step with a greedy algorithm.
///
/// The pivots are determined by looking at the conclusion clause: the terms in the premises that
/// are not present in the conclusion must have been eliminated, and are therefore pivots. This
/// algorithm may fail for some valid resolution steps, in which case reverse unit propagation is
/// needed.
///
/// If `tracing` is `true`, the pivot found in each binary resolution step is recorded in the
/// returned [`ResolutionTrace`].
pub fn greedy_resolution(
    conclusion: &[Rc<Term>],
    premises: &[&[Rc<Term>]],
    pool: &mut Pool,
    tracing: bool,
) -> Result<ResolutionTrace, ResolutionError> {
    // If we are elaborating, we record which pivot was found for each binary resolution step, so we
    // can add them all as arguments later
    let mut pivot_trace = Vec::new();

    // When checking this rule, we must look at what the conclusion clause looks like in order to
    // determine the pivots. The reason for that is because there is no other way to know which
    // terms should be removed in a given binary resolution step. Consider the following example,
    // adapted from an actual generated proof:
    //
    //     (step t1 (cl (not q) (not (not p)) (not p)) :rule irrelevant)
    //     (step t2 (cl (not (not (not p))) p) :rule irrelevant)
    //     (step t3 (cl (not q) p (not p)) :rule resolution :premises (t1 t2))
    //
    // Without looking at the conclusion, it is unclear if the (not p) term should be removed by the
    // p term, or if the (not (not p)) should be removed by the (not (not (not p))). We can only
    // determine this by looking at the conclusion and using it to derive the pivots.
    //
    // Note: for the hashmaps and hashsets used in this function we use `IndexSet`, to make sure
    // the iteration order is deterministic, as some error messages depend on that; and we use
    // `rapidhash::fast::RandomState`, to get a faster hash function.
    let conclusion: IndexSet<_, rapidhash::fast::RandomState> = conclusion
        .iter()
        .map(Rc::remove_all_negations)
        .map(|(n, t)| (n as i32, t))
        .collect();

    // The working clause contains the terms from the conclusion clause that we already encountered
    let mut working_clause: IndexSet<_, rapidhash::fast::RandomState> = IndexSet::default();

    // The pivots are the encountered terms that are not present in the conclusion clause, and so
    // should be removed. After being used to eliminate a term, a pivot can still be used to
    // eliminate other terms. Because of that, we represent the pivots as a hash map to a boolean,
    // which represents if the pivot was already eliminated or not. At the end, this boolean should
    // be true for all pivots
    let mut pivots: IndexMap<_, _, rapidhash::fast::RandomState> = IndexMap::default();

    for &premise in premises {
        // Only one pivot may be eliminated per clause. This restriction is required so logically
        // unsound proofs like this one are not considered valid:
        //
        //     (step t1 (cl (= false true) (not false) (not true)) :rule equiv_neg1)
        //     (step t2 (cl (= false true) false true) :rule equiv_neg2)
        //     (step t3 (cl (= false true)) :rule resolution :premises (t1 t2))
        let mut eliminated_clause_pivot = false;
        for term in premise {
            let (n, inner) = term.remove_all_negations();
            let n = n as i32;

            // There are two possible negations of a term, with one leading negation added, or with
            // one leading negation removed (if the term had any in the first place)
            let below = (n - 1, inner);
            let above = (n + 1, inner);

            // First, if the encountered term should be in the conclusion, but is not yet in the
            // working clause, we insert it and don't try to remove it with a pivot
            if conclusion.contains(&(n, inner)) && !working_clause.contains(&(n, inner)) {
                working_clause.insert((n, inner));
                continue;
            }

            // If the negation of the encountered term is present in the pivots set, we simply
            // eliminate it. Otherwise, we insert the encountered term in the working clause or the
            // pivots set, depending on whether it is present in the conclusion clause or not
            let mut try_eliminate = |pivot| match pivots.entry(pivot) {
                Entry::Occupied(mut e) => {
                    e.insert(true);
                    true
                }
                Entry::Vacant(_) => false,
            };

            // Only one pivot may be eliminated per clause, so if we already found this clauses'
            // pivot, we don't try to eliminate the term. If we are elaborating, we add the pivot
            // found to the pivot trace.
            let eliminated = if eliminated_clause_pivot {
                false
            } else if try_eliminate(below) {
                if tracing {
                    pivot_trace.push((literal_to_term(pool, (n as u32 - 1, inner)), true));
                }
                true
            } else if try_eliminate(above) {
                if tracing {
                    pivot_trace.push((term.clone(), false));
                }
                true
            } else {
                false
            };

            if eliminated {
                eliminated_clause_pivot = true;
            } else if conclusion.contains(&(n, inner)) {
                working_clause.insert((n, inner));
            } else {
                // If the term is not in the conclusion clause, it must be a pivot. If it was
                // not already in the pivots set, we insert `false`, to indicate that it was
                // not yet eliminated
                pivots.entry((n, inner)).or_insert(false);
            }
        }
    }

    // There are some special cases in the resolution rules that are valid, but leave a pivot
    // remaining
    let mut remaining_pivots = pivots.iter().filter(|&(_, eliminated)| !eliminated);

    if let Some(((i, pivot), _)) = remaining_pivots.next() {
        if remaining_pivots.next().is_none() {
            // There is a special case in the resolution rules that is valid, but leaves a pivot
            // remaining: when the result of the resolution is just the boolean constant `false`, it
            // may be implicitly eliminated. For example:
            //     (step t1 (cl p q false) :rule hole)
            //     (step t2 (cl (not p)) :rule hole)
            //     (step t3 (cl (not q)) :rule hole)
            //     (step t4 (cl) :rule resolution :premises (t1 t2 t3))
            if conclusion.is_empty() && *i == 0 && pivot.is_bool_false() {
                return Ok(ResolutionTrace { not_not_added: false, pivot_trace });
            }

            // There is another, similar, special case: when the result of the resolution is just
            // one term, it may appear in the conclusion clause with an even number of leading
            // negations added to it. The following is an example of this, adapted from a generated
            // proof:
            //     (step t1 (cl (not e)) :rule hole)
            //     (step t2 (cl (= (not e) (not (not f)))) :rule hole)
            //     (step t3 (cl (not (= (not e) (not (not f)))) e f) :rule hole)
            //     (step t4 (cl (not (not f))) :rule resolution :premises (t1 t2 t3))
            // Usually, we would expect the clause in the t4 step to be (cl f). This behavior may
            // be a bug in veriT, but it is still logically sound and happens often enough that it
            // is useful to support it here.
            if conclusion.len() == 1 {
                let (j, conclusion) = conclusion.into_iter().next().unwrap();
                if conclusion == *pivot && (i % 2) == (j % 2) {
                    return Ok(ResolutionTrace { not_not_added: true, pivot_trace });
                }
            }
        }
        let pivot = literal_to_term(pool, (*i as u32, pivot));
        Err(ResolutionError::RemainingPivot(pivot))
    } else {
        // This is the general case, where all pivots have been eliminated. In this case, the
        // working clause should be equal to the conclusion clause
        for (i, t) in conclusion {
            // By construction, the working clause is a subset of the conclusion. Therefore, we
            // only need to check that all terms in the conclusion are also in the working clause
            if !working_clause.contains(&(i, t)) {
                let t = literal_to_term(pool, (i as u32, t));
                return Err(ResolutionError::ExtraTermInConclusion(t));
            }
        }
        Ok(ResolutionTrace { not_not_added: false, pivot_trace })
    }
}
